
spring:
  datasource:
    username: 
    password: 
    url: 
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 
    port: 
    password: 
#  data:
#    neo4j:
#      uri: bolt://localhost:7687
#      username: neo4j
#      password: Ne04j

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
